version: '3'

services:
  ro-redis:
    container_name: ro-redis
    image: redis:3.2
    volumes:
      - ./output/redis:/data

  ro-db:
    container_name: ro-db
    image: mongo:3.0
    volumes:
      - ./output/mongo:/data/db

  ro-pull:
    container_name: ro-pull
    build:
      context: .
      dockerfile: ./pull/Dockerfile
    depends_on:
      - ro-redis
      - ro-process
      - ro-db
    command: ["./wait-for-it.sh", "ro-db:27017", "--", "npm", "start"]

  ro-process:
    container_name: ro-process
    build:
      context: .
      dockerfile: ./process/Dockerfile
    volumes:
      - ./output:/usr/db
    depends_on:
      - ro-redis
      - ro-db
    command: ["./wait-for-it.sh", "ro-db:27017", "--", "npm", "start"]

  # ro-front:
  #   container_name: ro-front
  #   build:
  #     context: .
  #     dockerfile: ./front/Dockerfile
  #   depends_on:
  #     - ro-db
  #   ports:
  #     - "3000-3005"
  #   command: ["./wait-for-it.sh", "ro-db:27017", "--", "node", "server.js"]
